import { ConnectManager } from "./connect_manager";
import { ChatManager } from "./chat_manager";
import { ChannelManager } from "./channel_manager";
import { TaskManager } from "./task";
import { ConversationManager } from "./conversation_manager";
import { SecurityManager } from "./security";
import { Channel, ChannelInfo, MediaMessageContent, Message, MessageContent, MessageContentManager, MessageText, SubscribeOption, SubscribeListener, UnsubscribeListener } from "./model";
import { ReminderManager } from "./reminder_manager";
import { WKConfig } from "./config";
import { ReceiptManager } from "./receipt_manager";
import { WKEventManager } from "./event_manager";
export default class WKSDK {
    config: WKConfig;
    messageContentManager: MessageContentManager;
    connectManager: ConnectManager;
    chatManager: ChatManager;
    channelManager: ChannelManager;
    taskManager: TaskManager;
    conversationManager: ConversationManager;
    reminderManager: ReminderManager;
    securityManager: SecurityManager;
    receiptManager: ReceiptManager;
    eventManager: WKEventManager;
    private static instance;
    static shared(): WKSDK;
    private init;
    register(contentType: number, handler: (contentType?: number) => MessageContent): void;
    registerFactor(factor: (contentType: number) => MessageContent | undefined): void;
    getMessageContent(contentType: number): MessageContent;
    isSystemMessage(contentType: number): boolean;
    connect(): void;
    disconnect(): void;
    onSubscribe(channel: Channel | string, listener: SubscribeListener, ...opts: SubscribeOption[]): void;
    onUnsubscribe(channel: Channel | string, listener?: UnsubscribeListener): void;
    newMessageText(text: string): MessageText;
    newChannel(channelID: string, channelType: number): Channel;
    newMessage(): Message;
    newChannelInfo(): ChannelInfo;
    newMediaMessageContent(): MediaMessageContent;
    newMessageContent(): MessageContent;
}
export { default as WKSDK } from "./index";
export * from "./model";
export * from "./const";
export * from "./conversation_manager";
export * from "./connect_manager";
export * from "./index";
export * from "./proto";
export * from "./chat_manager";
export * from "./task";
export * from "./channel_manager";
export * from "./provider";
export * from "./event_manager";
export * from "./config";
